### PR TITLE
To handle the new variation of Waveshare board

### PR DESCRIPTION
**Pull request by tokk-nv**

### CODE REVIEW

**Comment by tokk-nv** [comment]
Built images push to Docker Hub.

- `camera-0.4.2-32.4.4`
- `display-0.4.2-32.4.4`
- `jupyter-0.4.2-32.4.4`

https://hub.docker.com/r/jetbot/jetbot/tags

**Comment by tokk-nv** [comment]
Verified to work on
- DIY oepn-source JetBot with Jetson Nano (4GB)
- Waveshare JetBot (with 1 motor driver config) with Jetson Nano (4GB)
- Waveshare JetBot (with 2 motor driver config) with Jetson Nano (4GB)

**Comment by mmatesic01** [comment]
Hi.
Will this solution work on Jetson Nano 2GB version, also?
Thank you.

**Comment by tokk-nv** [comment]
Hi mmatesic01,
I will test this on Jetson Nano 2GB just in case, but it should work.

**Comment by mmatesic01** [comment]
> Hi mmatesic01,
> I will test this on Jetson Nano 2GB just in case, but it should work.

Hello,
Is this already applicable though "git clone http://github.com/NVIDIA-AI-IOT/jetbot.git" or do we have to wait?

**Comment by chitoku** [comment]
Once this Pull Request is approved and mereged, it is going to be avaialble on http://github.com/NVIDIA-AI-IOT/jetbot.git .

**Review by jaybdub — APPROVED** [review]

**Comment by jaybdub** [comment]
Merged.  As a note, we'll soon need to update the SD card setup to reference new images.

**Comment by mmatesic01** [comment]
I did the new docker installation (v 0.4.2) and I can confirm motors work with Waveshare now. (using Jetson Nano 2GB)

**Comment by tokk-nv** [comment]
We updated the SD card setup documentation with the new 0.4.2 image links.
http://jetbot.org/master/software_setup/sd_card.html

And thank you for your confirmation > mmatesic01.

**Pull request merged**
