### PR TITLE
Zmq default camera

### PR DESCRIPTION
**Pull request by jaybdub**
- switched default camera implementation to ZMQ camera
- added resize to (300,300) to object detector preprocessing, in case ZMQ camera is used (which is 224x224)

### CODE REVIEW

**Comment by tokk-nv** [comment]
Tested on freshly flashed JetPack 4.4 image, and got `OSError: libcurand.so.10: cannot open shared object file: No such file or directory` error...

```
Step 1/3 : ARG BASE_IMAGE=jetbot-base:jp44
Step 2/3 : FROM ${BASE_IMAGE}
 ---> a4941ea77fec
Step 3/3 : RUN python3 -c "import torchvision;                 model = torchvision.models.alexnet(pretrained=True);                 model = torchvision.models.squeezenet1_1(pretrained=True);                 model = torchvision.models.resnet18(pretrained=True);                 model = torchvision.models.resnet34(pretrained=True)"
 ---> Running in e5cfafef9e2b
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.7.0a0+6631b74-py3.6-linux-aarch64.egg/torchvision/__init__.py", line 5, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.7.0a0+6631b74-py3.6-linux-aarch64.egg/torchvision/models/__init__.py", line 1, in <module>
    from .alexnet import *
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.7.0a0+6631b74-py3.6-linux-aarch64.egg/torchvision/models/alexnet.py", line 1, in <module>
    import torch
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 188, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 141, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory
The command '/bin/sh -c python3 -c "import torchvision;                 model = torchvision.models.alexnet(pretrained=True);                 model = torchvision.models.squeezenet1_1(pretrained=True);                 model = torchvision.models.resnet18(pretrained=True);                 model = torchvision.models.resnet34(pretrained=True)"' returned a non-zero code: 1
./build.sh: line 5: cd: display: No such file or directory
./build.sh: line 6: cd: jupyter: No such file or directory
./build.sh: line 7: cd: camera: No such file or directory
```

**Comment by jaybdub** [comment]
Hmm, give it’s regarding torchvision it seems this is likely caused by update to PyTorch base container?

Were you able to resolve this, or still facing this issue?

**Comment by chitoku** [comment]
The `libcurand.so.10` related error was this.
https://github.com/dusty-nv/jetson-containers#docker-default-runtime
I committed a change on `build.sh` to do this (cd1f776). 

And it may also fix the jetbot ssd_tensorrt issue we were separately discussing (https://github.com/NVIDIA-AI-IOT/jetbot/pull/252#issuecomment-683297900)
Let me check that one as well.

**Comment by tokk-nv** [comment]
The `libcurand.so.10` related error was this.
https://github.com/dusty-nv/jetson-containers#docker-default-runtime
I committed a change on `build.sh` to do this (cd1f776). 

And it may also fix the jetbot ssd_tensorrt issue we were separately discussing (https://github.com/NVIDIA-AI-IOT/jetbot/pull/252#issuecomment-683297900)
Let me check that one as well.

**Comment by tokk-nv** [comment]
I think it did, although we still have some warnings.

```
-- Build files have been written to: /opt/jetbot
Scanning dependencies of target ssd_tensorrt
[ 50%] Building CXX object jetbot/ssd_tensorrt/CMakeFiles/ssd_tensorrt.dir/FlattenConcat.cpp.o
/opt/jetbot/jetbot/ssd_tensorrt/FlattenConcat.cpp: In member function 'virtual nvinfer1::Dims FlattenConcat::getOutputDimensions(int, const nvinfer1::Dims*, int)':
/opt/jetbot/jetbot/ssd_tensorrt/FlattenConcat.cpp:89:49: warning: 'DimsCHW' is deprecated [-Wdeprecated-declarations]
         return DimsCHW(flattenedOutputSize, 1, 1);
                                                 ^
In file included from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:53:0,
                 from /opt/jetbot/jetbot/ssd_tensorrt/FlattenConcat.cpp:9:
/usr/include/aarch64-linux-gnu/NvInfer.h:206:22: note: declared here
 class TRT_DEPRECATED DimsCHW : public Dims3
                      ^~~~~~~
/opt/jetbot/jetbot/ssd_tensorrt/FlattenConcat.cpp: In member function 'virtual bool FlattenConcat::supportsFormat(nvinfer1::DataType, nvinfer1::PluginFormat) const':
/opt/jetbot/jetbot/ssd_tensorrt/FlattenConcat.cpp:200:69: warning: 'kNCHW' is deprecated [-Wdeprecated-declarations]
         return (type == DataType::kFLOAT && format == PluginFormat::kNCHW);
                                                                     ^~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInferRuntime.h:59:0,
                 from /usr/include/aarch64-linux-gnu/NvInfer.h:53,
                 from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:53,
                 from /opt/jetbot/jetbot/ssd_tensorrt/FlattenConcat.cpp:9:
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:259:5: note: declared here
     kNCHW TRT_DEPRECATED_ENUM = kLINEAR, //!< Deprecated name of kLINEAR, provided for backwards compatibility
     ^~~~~
/opt/jetbot/jetbot/ssd_tensorrt/FlattenConcat.cpp:200:69: warning: 'kNCHW' is deprecated [-Wdeprecated-declarations]
         return (type == DataType::kFLOAT && format == PluginFormat::kNCHW);
                                                                     ^~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInferRuntime.h:59:0,
                 from /usr/include/aarch64-linux-gnu/NvInfer.h:53,
                 from /usr/include/aarch64-linux-gnu/NvInferPlugin.h:53,
                 from /opt/jetbot/jetbot/ssd_tensorrt/FlattenConcat.cpp:9:
/usr/include/aarch64-linux-gnu/NvInferRuntimeCommon.h:259:5: note: declared here
     kNCHW TRT_DEPRECATED_ENUM = kLINEAR, //!< Deprecated name of kLINEAR, provided for backwards compatibility
     ^~~~~
[100%] Linking CXX shared library libssd_tensorrt.so
[100%] Built target ssd_tensorrt
```

**Comment by jaybdub** [comment]
The deprecation warnings are OK I think.  At least they are unrelated to this pull request.

**Pull request merged**
