### PR TITLE
Typo in JETBOT_CAMERA environment variable

### PR DESCRIPTION
**Pull request by bezineb5**
When using a zmq_camera, it was set to {zmq_camera:-opencv_gst_camera}

### CODE REVIEW

**Comment by jaybdub** [comment]
Hi @bezineb5 ,

Great catch!  I just tested, your fix accomplishes what we intended.

Thanks!  

Out of curiosity -- are you using the zmq_camera.  If so, if you have any feedback on this alternative I'm curious to hear your experience with this.

Best,
John

**Review by jaybdub — APPROVED** [review]

**Comment by bezineb5** [comment]
Actually, I tried ZmqCamera as my camera was very unstable, with a 2Gb Jetson Nano. I opened ticket #363 for that because I cannot make collision_avoidance inference work on my setup. As if I couldn't have Pytorch and the camera running at the same time. Maybe 2Gb are not enough?

To be honest, I didn't see any difference between the ZmqCamera and the standard one, as it didn't help (the [changelog](https://github.com/NVIDIA-AI-IOT/jetbot/blob/master/CHANGELOG.md) mentioned it could have fixed the issue).

I'm using docker containers method to run everything, do you think it would make the camera more stable to run without docker?

PS: I also created #367, there's a tiny tiny bug which prevents the camera class to automatically select the right implementation.

**Comment by bezineb5** [comment]
I forgot to mention, but my hope is that the ZmqCamera is more robust if the camera is not closed at the end of a notebook - but I didn't manage to test that far!

**Comment by jaybdub** [comment]
ZmqCamera  should help with the second issue (not closing camera at end of notebook).  It actually may be possible to connect multiple notebooks simultaneously using ZmqCamera (not that I recommend this).

The camera crashing on 2GB likely has to do with the argus camera daemon running out of memory.  Both camera interfaces depend on the argus daemon, so it likely effects both.  To clarify, the issue I understand is that if the argus daemon runs out of physical RAM to use, it can crash.  

The way we prevented this with JetBot was by limiting the memory used by other processes (like the Jupyter Lab / Python).  This helps ensure that the argus daemon has enough physical RAM available to use.  Other processors will use SWAP memory when they hit their memory limit, so they still work.

Perhaps the memory limits aren't set on your jetson nano 2GB for some reason?

Do you mind sharing the output of

```bash
sudo docker stats
```

This should show the memory limit set for each jupyter container.

Best,
John

**Comment by jaybdub** [comment]
FYI, I created this issue here to discuss further on this issue.

https://github.com/NVIDIA-AI-IOT/jetbot/issues/368

**Pull request merged**
