### PR TITLE
default cam

### PR DESCRIPTION
**Pull request by jaybdub**

### CODE REVIEW

**Comment by tokk-nv** [comment]
Do we have `jetbot_camera` container still running?

**Comment by jaybdub** [comment]
Yes, In the current state of this pull request, but I'm working now on handling this.  

Also the ``Camera(...)`` constructor no longer returns a valid camera implementation.  This breaks road following notebook since it calls ``camera = Camera(...)`` directly rather than ``camera = Camera.instance(...)``.  I hadn't realized they called directly.  Working to see if this can be resolved.

I'll ping once these changes are in.

**Comment by jaybdub** [comment]
This PR is now ready for review.

**Comment by tokk-nv** [comment]
OK, I will check this branch.

**Review by tokk-nv — APPROVED** [review]

**Pull request merged**
