### PR TITLE
Add an optional training notebook with live graph (bokeh)

### PR DESCRIPTION
**Pull request by tokk-nv**

### CODE REVIEW

**Comment by jaybdub** [comment]
Small nit, but can we rename``train_model_graph`` -> ``train_model_plot`` or ``train_model_viz``.

My initial thought (from AI / compsci world) is computational graph, directed graph, etc.

**Comment by tokk-nv** [comment]
I see, sure, train_model_plot sounds good.

**Comment by jaybdub** [comment]
Just pinging.

Let me know once you've had the chance to make these changes.

**Comment by tokk-nv** [comment]
Changed the filename.

**Pull request merged**
