### PR TITLE
Docs - Change the color and nav structure

### PR DESCRIPTION
**Pull request by tokk-nv**

### CODE REVIEW

**Comment by tokk-nv** [comment]
https://tokk-nv.github.io/jetbot/

**Comment by ak-nv** [comment]
Do you want to add `DIY Open-Source JetBot Kit` similar to `3rd Party JetBot Kit` ?

**Comment by tokk-nv** [comment]
Modified the text in the image.

**Comment by ak-nv** [comment]
This looks as we discussed. I like the table, it is now clear.

**Review by ak-nv — APPROVED** [review]

**Pull request merged**
