### PR TITLE
0.4.2 image release on SD Card software setup page

### PR DESCRIPTION
**Pull request by tokk-nv**

### CODE REVIEW

**Comment by tokk-nv** [comment]
Draft push.
https://tokk-nv.github.io/jetbot/master/software_setup/sd_card.html

**Comment by tokk-nv** [comment]
The `gh-pages` branch (jetbot.org) has actually been updated from the local repo.

**Comment by tokk-nv** [comment]
This PR can be merged without risk as this is for docs only and had actually been push to jetbot.org.

@jaybdub , will you review this?

**Review by jaybdub — APPROVED** [review]
Approving since this is already in/promoted.

We should soon increment the python package version.  It's hung at 0.4.1.

**Comment by tokk-nv** [comment]
> We should soon increment the python package version.
Good point.

**Pull request merged**
